languageCode = "en"
languageName = "English"
weight = 1
title = "Digimente"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/transparent_logo.png"
  description = "Digimente, a mind forever voyaging."

[params.author]
  name = "Vicente Manuel Muñoz Milchorena"
  email = "vicente@milchorena.com"
  image = "img/vicosurge.jpeg"
  headline = "A mind forever voyaging."
  bio = "Cybersecurity Professional | Writer and Editor | People Person"
  links = [
    { linkedin = "https://www.linkedin.com/in/vicente-milchorena/" },
    { github = "https://github.com/vicosurge" },
    { website = "https://vicente.milchorena.com" },
  ]
