languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Vicente Manuel Muñoz Milchorena"
  email = "vicente@milchorena.com"
  image = "img/vicosurge.jpeg"
  headline = "A mind forever voyaging."
  bio = "Cybersecurity Professional | Writer and Editor | People Person"
  links = [
    { linkedin = "https://www.linkedin.com/in/vicente-milchorena/" },
    { github = "https://github.com/vicosurge" },
  ]
