baseURL = 'https://vicosurge.github.io/stories-as-code'
languageCode = 'en-us'
title = 'Digimente'
theme = 'blowfish'

[homepage]
  layout = "page"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

