name: Deploy Hugo site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.146.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Debug - List files
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Config file:"
          cat config.yaml || cat config.toml || echo "No config file found"
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
      - name: Debug - Check build output
        run: |
          echo "Build completed. Checking public directory:"
          ls -la public/ || echo "Public directory not found"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      
      # Slack notification for successful build
      - name: Slack Notification - Build Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#github'  # Change to your channel
          author_name: 'Hugo Build Bot'
          text: |
            ✅ *Hugo Build Completed*
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref_name }}
            *Commit:* ${{ github.event.head_commit.message }}
            *Build Status:* Compilation successful, ready for deployment
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      # Slack notification for failed build
      - name: Slack Notification - Build Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#github'  # Change to your channel
          author_name: 'Hugo Build Bot'
          text: |
            ❌ *Hugo Build Failed*
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref_name }}
            *Commit:* ${{ github.event.head_commit.message }}
            *Build Status:* Compilation failed - check logs for details
            
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Build Logs>
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      # Slack notification for successful deployment
      - name: Slack Notification - Deploy Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#deployments'  # Change to your channel
          author_name: 'Hugo Deploy Bot'
          text: |
            🚀 *Site Successfully Published*
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref_name }}
            *Site URL:* ${{ steps.deployment.outputs.page_url }}
            *Deploy Status:* Live and accessible
            
            <${{ steps.deployment.outputs.page_url }}|Visit Site> | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Deployment>
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      # Slack notification for failed deployment
      - name: Slack Notification - Deploy Failed
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#deployments'  # Change to your channel
          author_name: 'Hugo Deploy Bot'
          text: |
            💥 *Deployment Failed*
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref_name }}
            *Deploy Status:* Failed to publish to GitHub Pages
            
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Deployment Logs>
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
